var listPlayers = {
    "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
    "name": "Cowboys",
    "market": "Dallas",
    "alias": "DAL",
    "sr_id": "sr:competitor:4392",
    "franchise": {
        "id": "1e0f7b34-9603-412e-bcb6-358dbe5e9d6a",
        "name": "Cowboys",
        "alias": "DAL",
        "references": []
    },
    "venue": {
        "id": "1e84213a-ff1f-4c9d-a003-8ee782b25a40",
        "name": "AT&T Stadium",
        "city": "Arlington",
        "state": "TX",
        "country": "USA",
        "zip": "76011",
        "address": "One Legends Way",
        "capacity": 80000,
        "surface": "artificial",
        "roof_type": "retractable_dome",
        "sr_id": "sr:venue:6650",
        "location": {
            "lat": "32.747778",
            "lng": "-97.092778"
        }
    },
    "division": {
        "id": "6dab3ca1-b9cb-403f-91dd-b2a3708ab060",
        "name": "NFC East",
        "alias": "NFC_EAST"
    },
    "conference": {
        "id": "b1808e5f-d40b-47c0-8af8-5175c0fdcd26",
        "name": "NFC",
        "alias": "NFC"
    },
    "references": [],
    "coaches": [{
        "id": "2e347af9-be3a-43da-855a-68b994f4e40a",
        "full_name": "Dan Quinn",
        "first_name": "Dan",
        "last_name": "Quinn",
        "position": "Defensive Coordinator"
    }, {
        "id": "793d9b0d-0b96-4f64-aa8b-f5f7ae72c4ec",
        "full_name": "Kellen Moore",
        "first_name": "Kellen",
        "last_name": "Moore",
        "position": "Offensive Coordinator"
    }, {
        "id": "cf25a054-ebef-4dc2-b6c1-336f8e2af686",
        "full_name": "Mike McCarthy",
        "first_name": "Mike",
        "last_name": "McCarthy",
        "position": "Head Coach"
    }],
    "team_colors": [{
        "type": "secondary",
        "hex_color": "#869397",
        "alpha": 0.0,
        "rgb_color": {
            "red": 134,
            "green": 147,
            "blue": 151
        }
    }, {
        "type": "primary",
        "hex_color": "#002244",
        "alpha": 0.0,
        "rgb_color": {
            "red": 0,
            "green": 34,
            "blue": 68
        }
    }],
    "players": [{
        "id": "00cc0e57-b433-42e3-bc18-f7c4bc941a7f",
        "name": "Anthony Hines III",
        "jersey": "51",
        "last_name": "Hines",
        "first_name": "Anthony",
        "abbr_name": "A.Hines",
        "weight": 226.0,
        "height": 75,
        "position": "LB",
        "birth_place": "Plano, TX, USA",
        "high_school": "Plano East (TX)",
        "college": "Texas A&M",
        "status": "ACT",
        "sr_id": "sr:player:2198512",
        "name_suffix": "III"
    }, {
        "id": "00f88be8-45f9-4237-b2b8-3271ec790d07",
        "name": "Amari Cooper",
        "jersey": "19",
        "last_name": "Cooper",
        "first_name": "Amari",
        "abbr_name": "A.Cooper",
        "preferred_name": "Amari",
        "birth_date": "1994-06-17",
        "weight": 211.0,
        "height": 73,
        "position": "WR",
        "birth_place": "Miami, FL, USA",
        "high_school": "Northwestern (FL)",
        "college": "Alabama",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2015,
        "status": "ACT",
        "sr_id": "sr:player:834497",
        "draft": {
            "year": 2015,
            "round": 1,
            "number": 4,
            "team": {
                "id": "7d4fcc64-9cb5-4d1b-8e75-8a906d1e1576",
                "name": "Raiders",
                "market": "Las Vegas",
                "alias": "LV",
                "sr_id": "sr:competitor:4390"
            }
        }
    }, {
        "id": "026c284d-73fa-4391-9534-291bd12101ab",
        "name": "Brenden Knox",
        "jersey": "36",
        "last_name": "Knox",
        "first_name": "Brenden",
        "abbr_name": "B.Knox",
        "weight": 223.0,
        "height": 72,
        "position": "RB",
        "birth_place": "Columbus, OH, USA",
        "high_school": "Franklin Heights (OH)",
        "college": "Marshall",
        "status": "ACT",
        "sr_id": "sr:player:2198390"
    }, {
        "id": "02753dc9-52ac-4ed1-8086-7894d35a3bd1",
        "name": "Trevon Diggs",
        "jersey": "27",
        "last_name": "Diggs",
        "first_name": "Trevon",
        "abbr_name": "T.Diggs",
        "preferred_name": "Trevon",
        "birth_date": "1997-09-20",
        "weight": 207.0,
        "height": 74,
        "position": "CB",
        "birth_place": "Gaithersburg, MD, USA",
        "high_school": "Avalon School (MD)",
        "college": "Alabama",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040503",
        "draft": {
            "year": 2020,
            "round": 2,
            "number": 51,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "08d5875c-83aa-4ee8-aeab-dc3f7ee727e0",
        "name": "Nick Eubanks",
        "jersey": "47",
        "last_name": "Eubanks",
        "first_name": "Nick",
        "abbr_name": "N.Eubanks",
        "weight": 256.0,
        "height": 77,
        "position": "TE",
        "birth_place": "Plantation, FL, USA",
        "high_school": "American Heritage (FL)",
        "college": "Michigan",
        "status": "ACT",
        "sr_id": "sr:player:2198662"
    }, {
        "id": "08df3736-14f2-465e-af74-cdcdebe19a66",
        "name": "Aaron Parker",
        "jersey": "18",
        "last_name": "Parker",
        "first_name": "Aaron",
        "abbr_name": "A.Parker",
        "preferred_name": "Aaron",
        "birth_date": "1998-05-21",
        "weight": 191.0,
        "height": 75,
        "position": "WR",
        "birth_place": "Brandywine, MD, USA",
        "high_school": "Gwynn Park (MD)",
        "college": "Rhode Island",
        "college_conf": "Colonial Athletic Association",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040265"
    }, {
        "id": "09903f88-830a-4db2-8de7-1647c1f2eb6c",
        "name": "Osirus Mitchell",
        "jersey": "14",
        "last_name": "Mitchell",
        "first_name": "Osirus",
        "abbr_name": "O.Mitchell",
        "weight": 210.0,
        "height": 77,
        "position": "WR",
        "birth_place": "Sarasota, FL, USA",
        "high_school": "Booker (FL)",
        "college": "Mississippi State",
        "status": "ACT",
        "sr_id": "sr:player:2198806"
    }, {
        "id": "0bf6b11f-920a-4ced-9a69-0b4afc5df36f",
        "name": "Jaylon Smith",
        "jersey": "9",
        "last_name": "Smith",
        "first_name": "Jaylon",
        "abbr_name": "J.Smith",
        "preferred_name": "Jaylon",
        "birth_date": "1995-06-14",
        "weight": 245.0,
        "height": 74,
        "position": "LB",
        "birth_place": "Fort Wayne, IN, USA",
        "high_school": "Bishop Luers (IN)",
        "college": "Notre Dame",
        "college_conf": "Independent",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:987683",
        "draft": {
            "year": 2016,
            "round": 2,
            "number": 34,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "0c827cf4-d8ac-4efc-b030-019baa3c7216",
        "name": "Connor McGovern",
        "jersey": "66",
        "last_name": "McGovern",
        "first_name": "Connor",
        "abbr_name": "C.McGovern",
        "preferred_name": "Connor",
        "birth_date": "1997-11-03",
        "weight": 308.0,
        "height": 77,
        "position": "OG",
        "birth_place": "Larksville, PA, USA",
        "high_school": "Lake-Lehman (PA)",
        "college": "Penn State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1734807",
        "draft": {
            "year": 2019,
            "round": 3,
            "number": 90,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "0f369885-8ecd-4ca0-a3dc-df8530a0db6e",
        "name": "Sean McKeon",
        "jersey": "84",
        "last_name": "McKeon",
        "first_name": "Sean",
        "abbr_name": "S.McKeon",
        "preferred_name": "Sean",
        "birth_date": "1997-12-28",
        "weight": 246.0,
        "height": 77,
        "position": "TE",
        "birth_place": "Dudley, MA, USA",
        "high_school": "Shepherd Hill Regional (MA)",
        "college": "Michigan",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1218006"
    }, {
        "id": "1df2f078-18d8-4bb4-9d6a-9ba4bcb126bf",
        "name": "Carlos Watkins",
        "jersey": "91",
        "last_name": "Watkins",
        "first_name": "Carlos",
        "abbr_name": "C.Watkins",
        "preferred_name": "Carlos",
        "birth_date": "1993-12-05",
        "weight": 297.0,
        "height": 75,
        "position": "DE",
        "birth_place": "Forest City, NC, USA",
        "high_school": "Chase (NC)",
        "college": "Clemson",
        "college_conf": "Atlantic Coast Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130091",
        "draft": {
            "year": 2017,
            "round": 4,
            "number": 142,
            "team": {
                "id": "82d2d380-3834-4938-835f-aec541e5ece7",
                "name": "Texans",
                "market": "Houston",
                "alias": "HOU",
                "sr_id": "sr:competitor:4324"
            }
        }
    }, {
        "id": "1fb9a153-f1e0-4396-81fd-c3b1d331338f",
        "name": "Justin Hamilton",
        "jersey": "99",
        "last_name": "Hamilton",
        "first_name": "Justin",
        "abbr_name": "J.Hamilton",
        "preferred_name": "Justin",
        "birth_date": "1993-07-27",
        "weight": 315.0,
        "height": 74,
        "position": "DT",
        "birth_place": "Natchez, MS, USA",
        "high_school": "Natchez (MS)",
        "college": "Louisiana-Lafayette",
        "college_conf": "Sun Belt Conference",
        "rookie_year": 2015,
        "status": "ACT",
        "sr_id": "sr:player:853342"
    }, {
        "id": "22c50029-dccc-464e-81fe-236c34b167cd",
        "name": "Quinton Bohanna",
        "jersey": "98",
        "last_name": "Bohanna",
        "first_name": "Quinton",
        "abbr_name": "Q.Bohanna",
        "weight": 357.0,
        "height": 76,
        "position": "DT",
        "birth_place": "Memphis, TN, USA",
        "high_school": "Cordova (TN)",
        "college": "Kentucky",
        "status": "ACT",
        "sr_id": "sr:player:2198744",
        "draft": {
            "year": 2021,
            "round": 6,
            "number": 192,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "27ff4c5c-e34f-40a9-8dcb-b568cb52ae08",
        "name": "Braylon Jones",
        "jersey": "62",
        "last_name": "Jones",
        "first_name": "Braylon",
        "abbr_name": "B.Jones",
        "weight": 315.0,
        "height": 76,
        "position": "OL",
        "birth_place": "Tyler, TX, USA",
        "high_school": "John Tyler (TX)",
        "college": "Houston",
        "status": "ACT",
        "sr_id": "sr:player:2198626"
    }, {
        "id": "2dcc8e56-ac32-4774-a011-b1e65ca73786",
        "name": "Jeremy Sprinkle",
        "jersey": "87",
        "last_name": "Sprinkle",
        "first_name": "Jeremy",
        "abbr_name": "J.Sprinkle",
        "preferred_name": "Jeremy",
        "birth_date": "1994-08-10",
        "weight": 255.0,
        "height": 77,
        "position": "TE",
        "birth_place": "White Hall, AR, USA",
        "high_school": "White Hall (AR)",
        "college": "Arkansas",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130083",
        "draft": {
            "year": 2017,
            "round": 5,
            "number": 154,
            "team": {
                "id": "22052ff7-c065-42ee-bc8f-c4691c50e624",
                "name": "Football Team",
                "market": "Washington",
                "alias": "WAS",
                "sr_id": "sr:competitor:4432"
            }
        }
    }, {
        "id": "2e9e0b4e-d7f6-4d9b-850f-e1a5a8e17a5b",
        "name": "Ron'Dell Carter",
        "jersey": "97",
        "last_name": "Carter",
        "first_name": "Ron'Dell",
        "abbr_name": "R.Carter",
        "preferred_name": "Ron'Dell",
        "birth_date": "1997-07-03",
        "weight": 269.0,
        "height": 75,
        "position": "DE",
        "birth_place": "Baltimore, MD, USA",
        "high_school": "Long Reach (MD)",
        "college": "James Madison",
        "college_conf": "Colonial Athletic Association",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040349"
    }, {
        "id": "2e9ef3ac-eca5-4eb9-a41d-f404dfaae460",
        "name": "Donovan Wilson",
        "jersey": "6",
        "last_name": "Wilson",
        "first_name": "Donovan",
        "abbr_name": "D.Wilson",
        "preferred_name": "Donovan",
        "birth_date": "1997-03-14",
        "weight": 204.0,
        "height": 72,
        "position": "SAF",
        "birth_place": "Shreveport, LA, USA",
        "high_school": "Woodlawn (LA)",
        "college": "Texas A&amp;M",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1192098",
        "draft": {
            "year": 2019,
            "round": 6,
            "number": 213,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "2ff5e7ad-4ac1-4e26-9572-69bef348b1bc",
        "name": "La'el Collins",
        "jersey": "71",
        "last_name": "Collins",
        "first_name": "La'el",
        "abbr_name": "L.Collins",
        "preferred_name": "La'el",
        "birth_date": "1993-07-26",
        "weight": 320.0,
        "height": 76,
        "position": "OT",
        "birth_place": "Baton Rouge, LA, USA",
        "high_school": "Redemptorist (LA)",
        "college": "Louisiana State",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2015,
        "status": "ACT",
        "sr_id": "sr:player:837189"
    }, {
        "id": "3128aa52-4c62-4096-bf31-bef0fe8d6abc",
        "name": "Jake McQuaide",
        "jersey": "44",
        "last_name": "McQuaide",
        "first_name": "Jake",
        "abbr_name": "J.McQuaide",
        "preferred_name": "Jake",
        "birth_date": "1987-12-07",
        "weight": 235.0,
        "height": 74,
        "position": "LS",
        "birth_place": "Cincinnati, OH, USA",
        "high_school": "Elder (OH)",
        "college": "Ohio State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2011,
        "status": "ACT",
        "sr_id": "sr:player:829311"
    }, {
        "id": "32884cc4-ff90-42d0-b02b-f9a7df6ce6fb",
        "name": "Maurice Canady",
        "jersey": "31",
        "last_name": "Canady",
        "first_name": "Maurice",
        "abbr_name": "M.Canady",
        "preferred_name": "Maurice",
        "birth_date": "1994-05-26",
        "weight": 193.0,
        "height": 73,
        "position": "CB",
        "birth_place": "Richmond, VA, USA",
        "high_school": "Varina (VA)",
        "college": "Virginia",
        "college_conf": "Atlantic Coast Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:1073890",
        "draft": {
            "year": 2016,
            "round": 6,
            "number": 209,
            "team": {
                "id": "ebd87119-b331-4469-9ea6-d51fe3ce2f1c",
                "name": "Ravens",
                "market": "Baltimore",
                "alias": "BAL",
                "sr_id": "sr:competitor:4413"
            }
        }
    }, {
        "id": "33b0227d-4c21-4e71-b4cd-be35f7db9123",
        "name": "Tony Pollard",
        "jersey": "20",
        "last_name": "Pollard",
        "first_name": "Tony",
        "abbr_name": "T.Pollard",
        "preferred_name": "Tony",
        "birth_date": "1997-04-30",
        "weight": 209.0,
        "height": 72,
        "position": "RB",
        "birth_place": "Memphis, TN, USA",
        "high_school": "Melrose (TN)",
        "college": "Memphis",
        "college_conf": "American Athletic Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1189548",
        "draft": {
            "year": 2019,
            "round": 4,
            "number": 128,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "3411b31b-9800-4f5b-a43f-4564c9530627",
        "name": "Reggie Davis",
        "jersey": "16",
        "last_name": "Davis",
        "first_name": "Reggie",
        "abbr_name": "R.Davis",
        "preferred_name": "Reggie",
        "birth_date": "1995-11-22",
        "weight": 170.0,
        "height": 72,
        "position": "WR",
        "birth_place": "Tallahassee, FL, USA",
        "high_school": "Lincoln (FL)",
        "college": "Georgia",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1134727"
    }, {
        "id": "34e32cca-13c4-4a09-93b2-569cddb3c12e",
        "name": "Matt Farniok",
        "jersey": "68",
        "last_name": "Farniok",
        "first_name": "Matt",
        "abbr_name": "M.Farniok",
        "birth_date": "1997-09-26",
        "weight": 335.0,
        "height": 78,
        "position": "G",
        "birth_place": "Sioux Falls, SD, USA",
        "high_school": "Sioux Falls Washington (SD)",
        "college": "Nebraska",
        "status": "ACT",
        "sr_id": "sr:player:2197848",
        "draft": {
            "year": 2021,
            "round": 7,
            "number": 238,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "36f62824-1cdb-4e9e-8a11-55df97e562b9",
        "name": "Noah Brown",
        "jersey": "85",
        "last_name": "Brown",
        "first_name": "Noah",
        "abbr_name": "N.Brown",
        "preferred_name": "Noah",
        "birth_date": "1996-07-19",
        "weight": 225.0,
        "height": 74,
        "position": "WR",
        "birth_place": "Flanders, NJ, USA",
        "high_school": "Pope John XXIII (NJ)",
        "college": "Ohio State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130065",
        "draft": {
            "year": 2017,
            "round": 7,
            "number": 239,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "3860693c-99a2-4484-99db-1d43e3ff7fd4",
        "name": "Simi Fehoko",
        "jersey": "81",
        "last_name": "Fehoko",
        "first_name": "Simi",
        "abbr_name": "S.Fehoko",
        "weight": 220.0,
        "height": 76,
        "position": "WR",
        "birth_place": "Sandy, UT, USA",
        "high_school": "Brighton (UT)",
        "college": "Stanford",
        "status": "ACT",
        "sr_id": "sr:player:2198500",
        "draft": {
            "year": 2021,
            "round": 5,
            "number": 179,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "3cb26a5c-9c90-46ad-b539-e29ad6934e30",
        "name": "Malik Hooker",
        "jersey": "28",
        "last_name": "Hooker",
        "first_name": "Malik",
        "abbr_name": "M.Hooker",
        "preferred_name": "Malik",
        "birth_date": "1996-04-02",
        "weight": 212.0,
        "height": 73,
        "position": "SAF",
        "birth_place": "New Castle, PA, USA",
        "high_school": "New Castle (PA)",
        "college": "Ohio State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1129549",
        "draft": {
            "year": 2017,
            "round": 1,
            "number": 15,
            "team": {
                "id": "82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9",
                "name": "Colts",
                "market": "Indianapolis",
                "alias": "IND",
                "sr_id": "sr:competitor:4421"
            }
        }
    }, {
        "id": "3e3bd10a-6462-47f8-8938-42518781d060",
        "name": "DeMarcus Lawrence",
        "jersey": "90",
        "last_name": "Lawrence",
        "first_name": "Demarcus",
        "abbr_name": "D.Lawrence",
        "preferred_name": "Demarcus",
        "birth_date": "1992-04-28",
        "weight": 265.0,
        "height": 75,
        "position": "DE",
        "birth_place": "Aiken, SC, USA",
        "high_school": "Silver Bluff (SC)",
        "college": "Boise State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2014,
        "status": "ACT",
        "sr_id": "sr:player:855836",
        "draft": {
            "year": 2014,
            "round": 2,
            "number": 34,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "3ea081e8-a3c6-42c8-8deb-42a9bde10e98",
        "name": "JaQuan Hardy",
        "jersey": "37",
        "last_name": "Hardy",
        "first_name": "JaQuan",
        "abbr_name": "J.Hardy",
        "weight": 225.0,
        "height": 70,
        "position": "RB",
        "birth_place": "Westlake, OH, USA",
        "high_school": "Westlake (OH)",
        "college": "Tiffin (OH)",
        "status": "ACT",
        "sr_id": "sr:player:2198482"
    }, {
        "id": "3ec4f630-592c-4848-a76c-c30ecc090ecb",
        "name": "Darian Thompson",
        "jersey": "23",
        "last_name": "Thompson",
        "first_name": "Darian",
        "abbr_name": "D.Thompson",
        "preferred_name": "Darian",
        "birth_date": "1993-09-22",
        "weight": 213.0,
        "height": 74,
        "position": "SAF",
        "birth_place": "Lancaster, CA, USA",
        "high_school": "Paraclete (CA)",
        "college": "Boise State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:1074112",
        "draft": {
            "year": 2016,
            "round": 3,
            "number": 71,
            "team": {
                "id": "04aa1c9d-66da-489d-b16a-1dee3f2eec4d",
                "name": "Giants",
                "market": "New York",
                "alias": "NYG",
                "sr_id": "sr:competitor:4426"
            }
        }
    }, {
        "id": "3efde273-cfbe-4485-9ef1-d40ea147f99f",
        "name": "Kelvin Joseph",
        "jersey": "24",
        "last_name": "Joseph",
        "first_name": "Kelvin",
        "abbr_name": "K.Joseph",
        "birth_date": "2000-12-11",
        "weight": 192.0,
        "height": 73,
        "position": "CB",
        "birth_place": "Baton Rouge, LA, USA",
        "high_school": "Scotlandville Magnet (LA)",
        "college": "Kentucky",
        "status": "ACT",
        "sr_id": "sr:player:2197702",
        "draft": {
            "year": 2021,
            "round": 2,
            "number": 44,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "41bc429b-f4c2-4edd-bbe1-9a36a178caeb",
        "name": "Francis Bernard",
        "jersey": "53",
        "last_name": "Bernard",
        "first_name": "Francis",
        "abbr_name": "F.Bernard",
        "preferred_name": "Francis",
        "birth_date": "1995-04-08",
        "weight": 235.0,
        "height": 73,
        "position": "LB",
        "birth_place": "Herriman, UT, USA",
        "high_school": "Herriman (UT)",
        "college": "Utah",
        "college_conf": "Pacific Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1194576"
    }, {
        "id": "43211a61-4d89-4982-bbf1-9b932316b571",
        "name": "Steven Parker",
        "jersey": "25",
        "last_name": "Parker",
        "first_name": "Steven",
        "abbr_name": "S.Parker",
        "preferred_name": "Steven",
        "birth_date": "1995-12-14",
        "weight": 210.0,
        "height": 73,
        "position": "SAF",
        "birth_place": "Tulsa, OK, USA",
        "high_school": "Jenks (OK)",
        "college": "Oklahoma",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1216302"
    }, {
        "id": "43e8a6ac-d451-4dbd-b145-797764f91494",
        "name": "Blake Jarwin",
        "jersey": "89",
        "last_name": "Jarwin",
        "first_name": "Blake",
        "abbr_name": "B.Jarwin",
        "preferred_name": "Blake",
        "birth_date": "1994-07-16",
        "weight": 260.0,
        "height": 77,
        "position": "TE",
        "birth_place": "Oklahoma City, OK, USA",
        "high_school": "Tuttle (OK)",
        "college": "Oklahoma State",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130407"
    }, {
        "id": "4595c8ea-9d85-4504-8a34-2c8a02349105",
        "name": "Cooper Rush",
        "jersey": "10",
        "last_name": "Rush",
        "first_name": "Cooper",
        "abbr_name": "C.Rush",
        "preferred_name": "Cooper",
        "birth_date": "1993-11-21",
        "weight": 225.0,
        "height": 75,
        "position": "QB",
        "birth_place": "Charlotte, MI, USA",
        "high_school": "Lansing Catholic (MI)",
        "college": "Central Michigan",
        "college_conf": "Mid-American Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130393"
    }, {
        "id": "48efc038-96b7-4c63-a33c-41f6abe6d3de",
        "name": "Hunter Niswander",
        "jersey": "10",
        "last_name": "Niswander",
        "first_name": "Hunter",
        "abbr_name": "H.Niswander",
        "preferred_name": "Hunter",
        "birth_date": "1994-11-26",
        "weight": 243.0,
        "height": 77,
        "position": "P",
        "birth_place": "Peninsula, OH, USA",
        "high_school": "Woodridge (OH)",
        "college": "Northwestern",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2197690"
    }, {
        "id": "4a78d325-99ee-424c-bf79-33dc1bdada74",
        "name": "Jabril Cox",
        "jersey": "48",
        "last_name": "Cox",
        "first_name": "Jabril",
        "abbr_name": "J.Cox",
        "birth_date": "1998-04-16",
        "weight": 231.0,
        "height": 76,
        "position": "LB",
        "birth_place": "Kansas City, MO, USA",
        "high_school": "Raytown South (MO)",
        "college": "LSU",
        "status": "ACT",
        "sr_id": "sr:player:2197864",
        "draft": {
            "year": 2021,
            "round": 4,
            "number": 115,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "4a8fee2c-2870-42fa-8d71-429d36e057d2",
        "name": "Johnnie Dixon",
        "jersey": "6",
        "last_name": "Dixon",
        "first_name": "Johnnie",
        "abbr_name": "J.Dixon",
        "preferred_name": "Johnnie",
        "birth_date": "1994-09-16",
        "weight": 198.0,
        "height": 71,
        "position": "WR",
        "birth_place": "West Palm Beach, FL, USA",
        "high_school": "Dwyer (FL)",
        "college": "Ohio State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1219144"
    }, {
        "id": "5478c682-15ff-4932-97f3-6725c413c2c1",
        "name": "Isaac Alarcon",
        "jersey": "60",
        "last_name": "Alarcon",
        "first_name": "Isaac",
        "abbr_name": "I.Alarcon",
        "preferred_name": "Isaac",
        "birth_date": "1998-07-27",
        "weight": 301.0,
        "height": 79,
        "position": "OT",
        "birth_place": "Monterrey, Nuevo Leon, MEX",
        "high_school": "UANL (MEX)",
        "college": "No College",
        "college_conf": "NO COLLEGE",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2054005"
    }, {
        "id": "56073e7b-84ca-4d4a-a2e7-1bfc0277e8d4",
        "name": "Garrett Gilbert",
        "jersey": "3",
        "last_name": "Gilbert",
        "first_name": "Garrett",
        "abbr_name": "G.Gilbert",
        "preferred_name": "Garrett",
        "birth_date": "1991-01-01",
        "weight": 230.0,
        "height": 76,
        "position": "QB",
        "birth_place": "Buffalo, NY, USA",
        "high_school": "Lake Travis (TX)",
        "college": "Southern Methodist",
        "college_conf": "American Athletic Conference",
        "rookie_year": 2014,
        "status": "ACT",
        "sr_id": "sr:player:829755",
        "draft": {
            "year": 2014,
            "round": 6,
            "number": 214,
            "team": {
                "id": "39f349de-6463-4803-ad70-f1e0f144f5ed",
                "name": "Rams",
                "market": "St. Louis",
                "alias": "STL"
            }
        }
    }, {
        "id": "5a001d28-b271-410a-8c91-3159a6096258",
        "name": "Zack Martin",
        "jersey": "70",
        "last_name": "Martin",
        "first_name": "Zack",
        "abbr_name": "Z.Martin",
        "preferred_name": "Zack",
        "birth_date": "1990-11-20",
        "weight": 315.0,
        "height": 76,
        "position": "OG",
        "birth_place": "Indianapolis, IN, USA",
        "high_school": "Bishop Chatard (IN)",
        "college": "Notre Dame",
        "college_conf": "Independent",
        "rookie_year": 2014,
        "status": "ACT",
        "sr_id": "sr:player:855670",
        "draft": {
            "year": 2014,
            "round": 1,
            "number": 16,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "5bc24739-494e-4d0c-beae-e15231743bcf",
        "name": "Osa Odighizuwa",
        "jersey": "75",
        "last_name": "Odighizuwa",
        "first_name": "Osa",
        "abbr_name": "O.Odighizuwa",
        "birth_date": "1998-08-13",
        "weight": 279.0,
        "height": 74,
        "position": "DT",
        "birth_place": "Dayton, OH, USA",
        "high_school": "David Douglas (OR)",
        "college": "UCLA",
        "status": "ACT",
        "sr_id": "sr:player:2197940",
        "draft": {
            "year": 2021,
            "round": 3,
            "number": 75,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "5c913725-c52a-4633-b3b9-efa6a9d2cf05",
        "name": "Randy Gregory",
        "jersey": "94",
        "last_name": "Gregory",
        "first_name": "Randy",
        "abbr_name": "R.Gregory",
        "preferred_name": "Randy",
        "birth_date": "1992-11-23",
        "weight": 255.0,
        "height": 77,
        "position": "DE",
        "birth_place": "Fishers, IN, USA",
        "high_school": "Hamilton Southeastern (IN)",
        "college": "Nebraska",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2015,
        "status": "ACT",
        "sr_id": "sr:player:834751",
        "draft": {
            "year": 2015,
            "round": 2,
            "number": 60,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "63cef4ac-6e22-497b-9f8c-fbccd0694d17",
        "name": "Brent Urban",
        "jersey": "95",
        "last_name": "Urban",
        "first_name": "Brent",
        "abbr_name": "B.Urban",
        "preferred_name": "Brent",
        "birth_date": "1991-05-05",
        "weight": 300.0,
        "height": 79,
        "position": "DE",
        "birth_place": "Mississauga, ON, CAN",
        "high_school": "Lorne Park Secondary (CAN)",
        "college": "Virginia",
        "college_conf": "Atlantic Coast Conference",
        "rookie_year": 2014,
        "status": "ACT",
        "sr_id": "sr:player:833327",
        "draft": {
            "year": 2014,
            "round": 4,
            "number": 134,
            "team": {
                "id": "ebd87119-b331-4469-9ea6-d51fe3ce2f1c",
                "name": "Ravens",
                "market": "Baltimore",
                "alias": "BAL",
                "sr_id": "sr:competitor:4413"
            }
        }
    }, {
        "id": "6445ca00-93b4-46d8-8ac6-451ae70a75f5",
        "name": "Anthony Brown",
        "jersey": "30",
        "last_name": "Brown",
        "first_name": "Anthony",
        "abbr_name": "A.Brown",
        "preferred_name": "Anthony",
        "birth_date": "1993-12-15",
        "weight": 196.0,
        "height": 71,
        "position": "CB",
        "birth_place": "Tampa, FL, USA",
        "high_school": "Hillsborough (FL)",
        "college": "Purdue",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:988787",
        "draft": {
            "year": 2016,
            "round": 6,
            "number": 189,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "6d62aaa2-fe41-4672-941f-7314a0b9b367",
        "name": "C.J. Goodwin",
        "jersey": "29",
        "last_name": "Goodwin",
        "first_name": "C.J.",
        "abbr_name": "C.Goodwin",
        "preferred_name": "C.J.",
        "birth_date": "1990-02-04",
        "weight": 190.0,
        "height": 75,
        "position": "CB",
        "birth_place": "Wheeling, WV, USA",
        "high_school": "Linsly School (WV)",
        "college": "California, Pa.",
        "college_conf": "Pennsylvania State Athletic Conference",
        "rookie_year": 2014,
        "status": "ACT",
        "sr_id": "sr:player:833703"
    }, {
        "id": "6ee71282-c2b8-416a-8de1-29c0185d9b7b",
        "name": "Bryan Anger",
        "jersey": "5",
        "last_name": "Anger",
        "first_name": "Bryan",
        "abbr_name": "B.Anger",
        "preferred_name": "Bryan",
        "birth_date": "1988-10-06",
        "weight": 205.0,
        "height": 75,
        "position": "P",
        "birth_place": "Camarillo, CA, USA",
        "high_school": "Camarillo (CA)",
        "college": "California",
        "college_conf": "Pacific Twelve Conference",
        "rookie_year": 2012,
        "status": "ACT",
        "sr_id": "sr:player:828911",
        "draft": {
            "year": 2012,
            "round": 3,
            "number": 70,
            "team": {
                "id": "f7ddd7fa-0bae-4f90-bc8e-669e4d6cf2de",
                "name": "Jaguars",
                "market": "Jacksonville",
                "alias": "JAC",
                "sr_id": "sr:competitor:4386"
            }
        }
    }, {
        "id": "708e045b-17fd-4f81-87e3-8686b165a278",
        "name": "Jayron Kearse",
        "jersey": "32",
        "last_name": "Kearse",
        "first_name": "Jayron",
        "abbr_name": "J.Kearse",
        "preferred_name": "Jayron",
        "birth_date": "1994-02-11",
        "weight": 215.0,
        "height": 76,
        "position": "SAF",
        "birth_place": "Fort Myers, FL, USA",
        "high_school": "South Fort Myers (FL)",
        "college": "Clemson",
        "college_conf": "Atlantic Coast Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:988625",
        "draft": {
            "year": 2016,
            "round": 7,
            "number": 244,
            "team": {
                "id": "33405046-04ee-4058-a950-d606f8c30852",
                "name": "Vikings",
                "market": "Minnesota",
                "alias": "MIN",
                "sr_id": "sr:competitor:4423"
            }
        }
    }, {
        "id": "7111b5cc-d74b-416b-9c93-c2fdf7ad193e",
        "name": "Israel Mukuamu",
        "jersey": "38",
        "last_name": "Mukuamu",
        "first_name": "Israel",
        "abbr_name": "I.Mukuamu",
        "birth_date": "1999-11-28",
        "weight": 205.0,
        "height": 76,
        "position": "CB",
        "birth_place": "Bossier City, LA, USA",
        "high_school": "Parkway (LA)",
        "college": "South Carolina",
        "status": "ACT",
        "sr_id": "sr:player:2198010",
        "draft": {
            "year": 2021,
            "round": 6,
            "number": 227,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "79c0e337-bc7b-4abc-9660-0d919251c83b",
        "name": "Josh Ball",
        "jersey": "76",
        "last_name": "Ball",
        "first_name": "Josh",
        "abbr_name": "J.Ball",
        "birth_date": "1998-05-15",
        "weight": 309.0,
        "height": 80,
        "position": "OT",
        "birth_place": "Fredericksburg, VA, USA",
        "high_school": "Stafford Senior (VA)",
        "college": "Marshall",
        "status": "ACT",
        "sr_id": "sr:player:2197666",
        "draft": {
            "year": 2021,
            "round": 4,
            "number": 138,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "7ff68f1d-204c-4d49-9179-ecb2514094dc",
        "name": "Jourdan Lewis",
        "jersey": "26",
        "last_name": "Lewis",
        "first_name": "Jourdan",
        "abbr_name": "J.Lewis",
        "preferred_name": "Jourdan",
        "birth_date": "1995-08-31",
        "weight": 195.0,
        "height": 70,
        "position": "CB",
        "birth_place": "Detroit, MI, USA",
        "high_school": "Cass Tech (MI)",
        "college": "Michigan",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1129859",
        "draft": {
            "year": 2017,
            "round": 3,
            "number": 92,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "82a7e1ff-019a-4f4b-aeb6-c41420e44891",
        "name": "Malik Turner",
        "jersey": "17",
        "last_name": "Turner",
        "first_name": "Malik",
        "abbr_name": "M.Turner",
        "preferred_name": "Malik",
        "birth_date": "1996-01-30",
        "weight": 200.0,
        "height": 74,
        "position": "WR",
        "birth_place": "Springfield, IL, USA",
        "high_school": "Sacred Heart-Griffin (IL)",
        "college": "Illinois",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1552571"
    }, {
        "id": "854d07f2-11cc-4dc1-bdaf-e8cce2c89a75",
        "name": "Bradlee Anae",
        "jersey": "56",
        "last_name": "Anae",
        "first_name": "Bradlee",
        "abbr_name": "B.Anae",
        "preferred_name": "Bradlee",
        "birth_date": "1998-01-17",
        "weight": 265.0,
        "height": 75,
        "position": "DE",
        "birth_place": "Laie, HI, USA",
        "high_school": "Kahuku (HI)",
        "college": "Utah",
        "college_conf": "Pacific Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040049",
        "draft": {
            "year": 2020,
            "round": 5,
            "number": 179,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "86197778-8d4b-4eba-affe-08ef7be7c70b",
        "name": "Dak Prescott",
        "jersey": "4",
        "last_name": "Prescott",
        "first_name": "Dak",
        "abbr_name": "D.Prescott",
        "preferred_name": "Dak",
        "birth_date": "1993-07-29",
        "weight": 238.0,
        "height": 74,
        "position": "QB",
        "birth_place": "Sulphur, LA, USA",
        "high_school": "Haughton (LA)",
        "college": "Mississippi State",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:988663",
        "draft": {
            "year": 2016,
            "round": 4,
            "number": 135,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "884b6094-1ebd-4b72-b957-ad33a3ab984f",
        "name": "Nahshon Wright",
        "jersey": "40",
        "last_name": "Wright",
        "first_name": "Nahshon",
        "abbr_name": "N.Wright",
        "birth_date": "1998-09-23",
        "weight": 188.0,
        "height": 76,
        "position": "CB",
        "birth_place": "East Palo Alto, CA, USA",
        "high_school": "James Logan (CA)",
        "college": "Oregon State",
        "status": "ACT",
        "sr_id": "sr:player:2197976",
        "draft": {
            "year": 2021,
            "round": 3,
            "number": 99,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "8caec1b4-e0b6-4a84-b8c8-617d6e91ef6a",
        "name": "Dalton Schultz",
        "jersey": "86",
        "last_name": "Schultz",
        "first_name": "Dalton",
        "abbr_name": "D.Schultz",
        "preferred_name": "Dalton",
        "birth_date": "1996-07-11",
        "weight": 242.0,
        "height": 77,
        "position": "TE",
        "birth_place": "Sandy, UT, USA",
        "high_school": "Bingham (UT)",
        "college": "Stanford",
        "college_conf": "Pacific Twelve Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1191862",
        "draft": {
            "year": 2018,
            "round": 4,
            "number": 137,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "96d94c76-9563-460a-91e5-47b99f29587b",
        "name": "Connor Williams",
        "jersey": "52",
        "last_name": "Williams",
        "first_name": "Connor",
        "abbr_name": "C.Williams",
        "preferred_name": "Connor",
        "birth_date": "1997-05-12",
        "weight": 298.0,
        "height": 77,
        "position": "OG",
        "birth_place": "Coppell, TX, USA",
        "high_school": "Coppell (TX)",
        "college": "Texas",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1225224",
        "draft": {
            "year": 2018,
            "round": 2,
            "number": 50,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "9b1a3246-4f3b-47f7-9bf8-a33d6e454723",
        "name": "Terence Steele",
        "jersey": "78",
        "last_name": "Steele",
        "first_name": "Terence",
        "abbr_name": "T.Steele",
        "preferred_name": "Terence",
        "birth_date": "1997-06-04",
        "weight": 310.0,
        "height": 78,
        "position": "OL",
        "birth_place": "Cibolo, TX, USA",
        "high_school": "Steele (TX)",
        "college": "Texas Tech",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1226784"
    }, {
        "id": "9e174ff2-ca0e-4e6b-96f7-90f0088f7edd",
        "name": "Michael Gallup",
        "jersey": "13",
        "last_name": "Gallup",
        "first_name": "Michael",
        "abbr_name": "M.Gallup",
        "preferred_name": "Michael",
        "birth_date": "1996-03-04",
        "weight": 200.0,
        "height": 73,
        "position": "WR",
        "birth_place": "Atlanta, GA, USA",
        "high_school": "Monroe (GA)",
        "college": "Colorado State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1474002",
        "draft": {
            "year": 2018,
            "round": 3,
            "number": 81,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "a28daf84-6354-49e6-a047-1bc549997f29",
        "name": "Dorance Armstrong Jr.",
        "jersey": "92",
        "last_name": "Armstrong",
        "first_name": "Dorance",
        "abbr_name": "D.Armstrong",
        "preferred_name": "Dorance",
        "birth_date": "1997-06-10",
        "weight": 255.0,
        "height": 76,
        "position": "DE",
        "birth_place": "Houston, TX, USA",
        "high_school": "North Shore (TX)",
        "college": "Kansas",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1475046",
        "name_suffix": "Jr.",
        "draft": {
            "year": 2018,
            "round": 4,
            "number": 116,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "a72ea15b-5199-4101-a300-846e1c655add",
        "name": "CeeDee Lamb",
        "jersey": "88",
        "last_name": "Lamb",
        "first_name": "CeeDee",
        "abbr_name": "C.Lamb",
        "preferred_name": "CeeDee",
        "birth_date": "1999-04-08",
        "weight": 189.0,
        "height": 74,
        "position": "WR",
        "birth_place": "Richmond, TX, USA",
        "high_school": "Foster (TX)",
        "college": "Oklahoma",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040323",
        "draft": {
            "year": 2020,
            "round": 1,
            "number": 17,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "a964f59b-af2b-48e1-b64d-c376cc1d8c28",
        "name": "Cedrick Wilson",
        "jersey": "1",
        "last_name": "Wilson",
        "first_name": "Cedrick",
        "abbr_name": "C.Wilson",
        "preferred_name": "Cedrick",
        "birth_date": "1995-11-20",
        "weight": 188.0,
        "height": 77,
        "position": "WR",
        "birth_place": "Memphis, TN, USA",
        "high_school": "White Station (TN)",
        "college": "Boise State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1184492",
        "draft": {
            "year": 2018,
            "round": 6,
            "number": 208,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "af433e33-5d77-47fd-b6ef-70815e6aa0a1",
        "name": "Deante Burton",
        "jersey": "33",
        "last_name": "Burton",
        "first_name": "Deante",
        "abbr_name": "D.Burton",
        "preferred_name": "Deante",
        "birth_date": "1994-07-12",
        "weight": 205.0,
        "height": 74,
        "position": "CB",
        "birth_place": "Manhattan, KS, USA",
        "high_school": "Manhattan (KS)",
        "college": "Kansas State",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1131017"
    }, {
        "id": "b4eab0bf-9e1f-43f8-912f-d33ac517bc46",
        "name": "Micah Parsons",
        "jersey": "11",
        "last_name": "Parsons",
        "first_name": "Micah",
        "abbr_name": "M.Parsons",
        "birth_date": "1999-05-26",
        "weight": 245.0,
        "height": 75,
        "position": "LB",
        "birth_place": "Harrisburg, PA, USA",
        "high_school": "Harrisburg (PA)",
        "college": "Penn State",
        "status": "ACT",
        "sr_id": "sr:player:2197938",
        "draft": {
            "year": 2021,
            "round": 1,
            "number": 12,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "b67f1dea-6093-4109-8c0a-ded4ff0e1984",
        "name": "Brennan Eagles",
        "jersey": "83",
        "last_name": "Eagles",
        "first_name": "Brennan",
        "abbr_name": "B.Eagles",
        "weight": 229.0,
        "height": 76,
        "position": "WR",
        "birth_place": "Houston, TX, USA",
        "high_school": "Alief Taylor (TX)",
        "college": "Texas",
        "status": "ACT",
        "sr_id": "sr:player:1423059"
    }, {
        "id": "b6ab79d0-cbb6-4e2c-8a9d-2e4a092325bc",
        "name": "Leighton Vander Esch",
        "jersey": "55",
        "last_name": "Vander Esch",
        "first_name": "Leighton",
        "abbr_name": "L.Vander Esch",
        "preferred_name": "Leighton",
        "birth_date": "1997-02-09",
        "weight": 256.0,
        "height": 76,
        "position": "LB",
        "birth_place": "Riggins, ID, USA",
        "high_school": "Salmon River (ID)",
        "college": "Boise State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2018,
        "status": "ACT",
        "sr_id": "sr:player:1205030",
        "draft": {
            "year": 2018,
            "round": 1,
            "number": 19,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "bba755a2-63b6-4ac1-b806-0609816135de",
        "name": "Rico Dowdle",
        "jersey": "34",
        "last_name": "Dowdle",
        "first_name": "Rico",
        "abbr_name": "R.Dowdle",
        "preferred_name": "Rico",
        "birth_date": "1998-06-14",
        "weight": 215.0,
        "height": 72,
        "position": "RB",
        "birth_place": "Asheville, NC, USA",
        "high_school": "A.C. Reynolds (NC)",
        "college": "South Carolina",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1216648"
    }, {
        "id": "bc8260d5-231f-4337-9979-7c1c40bc6cd0",
        "name": "Luke Gifford",
        "jersey": "57",
        "last_name": "Gifford",
        "first_name": "Luke",
        "abbr_name": "L.Gifford",
        "preferred_name": "Luke",
        "birth_date": "1995-08-28",
        "weight": 245.0,
        "height": 75,
        "position": "LB",
        "birth_place": "Lincoln, NE, USA",
        "high_school": "Lincoln Southeast (NE)",
        "college": "Nebraska",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1229166"
    }, {
        "id": "bef8b2b4-78bd-4a4d-bb5d-6b55ada9ef6a",
        "name": "Ezekiel Elliott",
        "jersey": "21",
        "last_name": "Elliott",
        "first_name": "Ezekiel",
        "abbr_name": "E.Elliott",
        "preferred_name": "Ezekiel",
        "birth_date": "1995-07-22",
        "weight": 228.0,
        "height": 72,
        "position": "RB",
        "birth_place": "Alton, IL, USA",
        "high_school": "John Burroughs (MO)",
        "college": "Ohio State",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:986887",
        "draft": {
            "year": 2016,
            "round": 1,
            "number": 4,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "c3b8df6d-c6b7-43f0-a902-fbb7e70fa2e3",
        "name": "Artayvious Lynn",
        "jersey": "49",
        "last_name": "Lynn",
        "first_name": "Artayvious",
        "abbr_name": "A.Lynn",
        "weight": 258.0,
        "height": 78,
        "position": "TE",
        "birth_place": "Bossier City, LA, USA",
        "high_school": "Parkway (LA)",
        "college": "TCU",
        "status": "ACT",
        "sr_id": "sr:player:1220288"
    }, {
        "id": "c3f2ea91-98d6-4d37-b5bd-3c7ac07e5b24",
        "name": "Tyron Smith",
        "jersey": "77",
        "last_name": "Smith",
        "first_name": "Tyron",
        "abbr_name": "T.Smith",
        "preferred_name": "Tyron",
        "birth_date": "1990-12-12",
        "weight": 320.0,
        "height": 77,
        "position": "OT",
        "birth_place": "Los Angeles, CA, USA",
        "high_school": "Rancho Verde (CA)",
        "college": "Southern California",
        "college_conf": "Pacific Twelve Conference",
        "rookie_year": 2011,
        "status": "ACT",
        "sr_id": "sr:player:829389",
        "draft": {
            "year": 2011,
            "round": 1,
            "number": 9,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "c4e6f302-b6a0-431d-a1f0-25efa2e7a8c7",
        "name": "Nick Ralston",
        "jersey": "46",
        "last_name": "Ralston",
        "first_name": "Nick",
        "abbr_name": "N.Ralston",
        "birth_date": "1996-11-10",
        "weight": 240.0,
        "height": 73,
        "position": "FB",
        "birth_place": "Dallas, TX, USA",
        "high_school": "Argyle (TX)",
        "college": "Louisiana-Lafayette",
        "status": "ACT",
        "sr_id": "sr:player:2197782"
    }, {
        "id": "c744ade6-bce2-4c71-8f1b-742cb183c8eb",
        "name": "Ben DiNucci",
        "jersey": "7",
        "last_name": "DiNucci",
        "first_name": "Ben",
        "abbr_name": "B.DiNucci",
        "preferred_name": "Ben",
        "birth_date": "1996-11-24",
        "weight": 210.0,
        "height": 75,
        "position": "QB",
        "birth_place": "Wexford, PA, USA",
        "high_school": "Pine-Richland (PA)",
        "college": "James Madison",
        "college_conf": "Colonial Athletic Association",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1230242",
        "draft": {
            "year": 2020,
            "round": 7,
            "number": 231,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "c9ef678b-959b-445b-b32a-81c767c8ad65",
        "name": "Brandon Smith",
        "jersey": "80",
        "last_name": "Smith",
        "first_name": "Brandon",
        "abbr_name": "B.Smith",
        "weight": 319.0,
        "height": 75,
        "position": "WR",
        "birth_place": "Lake Cormorant, MS, USA",
        "high_school": "Lake Cormorant (MS)",
        "college": "Iowa",
        "status": "ACT",
        "sr_id": "sr:player:1485722"
    }, {
        "id": "cc9c2006-e72b-4073-afcc-69c187cb28b7",
        "name": "Keanu Neal",
        "jersey": "42",
        "last_name": "Neal",
        "first_name": "Keanu",
        "abbr_name": "K.Neal",
        "preferred_name": "Keanu",
        "birth_date": "1995-07-26",
        "weight": 216.0,
        "height": 73,
        "position": "LB",
        "birth_place": "Bushnell, FL, USA",
        "high_school": "South Sumter (FL)",
        "college": "Florida",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2016,
        "status": "ACT",
        "sr_id": "sr:player:1074202",
        "draft": {
            "year": 2016,
            "round": 1,
            "number": 17,
            "team": {
                "id": "e6aa13a4-0055-48a9-bc41-be28dc106929",
                "name": "Falcons",
                "market": "Atlanta",
                "alias": "ATL",
                "sr_id": "sr:competitor:4393"
            }
        }
    }, {
        "id": "cf93a57e-129e-4e81-8d40-d8772ee0403c",
        "name": "Kyron Brown",
        "jersey": "36",
        "last_name": "Brown",
        "first_name": "Kyron",
        "abbr_name": "K.Brown",
        "preferred_name": "Kyron",
        "birth_date": "1996-05-26",
        "weight": 195.0,
        "height": 73,
        "position": "CB",
        "birth_place": "Boynton Beach, FL, USA",
        "high_school": "Boynton Beach (FL)",
        "college": "Akron",
        "college_conf": "Mid-American Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1735063"
    }, {
        "id": "d7068799-55b7-47c2-91d9-0e532957939e",
        "name": "Tarell Basham",
        "jersey": "93",
        "last_name": "Basham",
        "first_name": "Tarell",
        "abbr_name": "T.Basham",
        "preferred_name": "Tarell",
        "birth_date": "1994-03-18",
        "weight": 266.0,
        "height": 76,
        "position": "DE",
        "birth_place": "Rocky Mount, VA, USA",
        "high_school": "Franklin County (VA)",
        "college": "Ohio",
        "college_conf": "Mid-American Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1129807",
        "draft": {
            "year": 2017,
            "round": 3,
            "number": 80,
            "team": {
                "id": "82cf9565-6eb9-4f01-bdbd-5aa0d472fcd9",
                "name": "Colts",
                "market": "Indianapolis",
                "alias": "IND",
                "sr_id": "sr:competitor:4421"
            }
        }
    }, {
        "id": "d723ebff-0e9d-42f8-93d2-fe0c02252de8",
        "name": "Ty Nsekhe",
        "jersey": "79",
        "last_name": "Nsekhe",
        "first_name": "Ty",
        "abbr_name": "T.Nsekhe",
        "preferred_name": "Ty",
        "birth_date": "1985-10-27",
        "weight": 330.0,
        "height": 80,
        "position": "OT",
        "birth_place": "Brooklyn, NY, USA",
        "high_school": "James Bowie (TX)",
        "college": "Texas State",
        "college_conf": "Sun Belt Conference",
        "rookie_year": 2012,
        "status": "ACT",
        "sr_id": "sr:player:827649"
    }, {
        "id": "dfccabc2-00ba-4eef-9686-1e1aff2f1dbc",
        "name": "Tyler Coyle",
        "jersey": "39",
        "last_name": "Coyle",
        "first_name": "Tyler",
        "abbr_name": "T.Coyle",
        "weight": 215.0,
        "height": 74,
        "position": "SAF",
        "birth_place": "Windsor, CT, USA",
        "high_school": "Windsor (CT)",
        "college": "Purdue",
        "status": "ACT",
        "sr_id": "sr:player:2198542"
    }, {
        "id": "e1705a56-ae89-4af7-baac-4e72b6f7bd7a",
        "name": "Brandon Knight",
        "jersey": "69",
        "last_name": "Knight",
        "first_name": "Brandon",
        "abbr_name": "B.Knight",
        "preferred_name": "Brandon",
        "birth_date": "1997-04-01",
        "weight": 314.0,
        "height": 77,
        "position": "OT",
        "birth_place": "Noblesville, IN, USA",
        "high_school": "Noblesville (IN)",
        "college": "Indiana",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2019,
        "status": "ACT",
        "sr_id": "sr:player:1217642"
    }, {
        "id": "e44308c4-2505-4b79-855a-18d83d407fc5",
        "name": "Reggie Robinson II",
        "jersey": "41",
        "last_name": "Robinson",
        "first_name": "Reggie",
        "abbr_name": "R.Robinson",
        "preferred_name": "Reggie",
        "birth_date": "1997-04-14",
        "weight": 197.0,
        "height": 73,
        "position": "CB",
        "birth_place": "Cleburne, TX, USA",
        "high_school": "Cleburne (TX)",
        "college": "Tulsa",
        "college_conf": "American Athletic Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040113",
        "name_suffix": "II",
        "draft": {
            "year": 2020,
            "round": 4,
            "number": 123,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "e479ff14-6e5f-42a2-8b05-bca76c62111d",
        "name": "Stephen Guidry",
        "jersey": "16",
        "last_name": "Guidry",
        "first_name": "Stephen",
        "abbr_name": "S.Guidry",
        "preferred_name": "Stephen",
        "birth_date": "1997-03-25",
        "weight": 200.0,
        "height": 76,
        "position": "WR",
        "birth_place": "New Roads, LA, USA",
        "high_school": "Livonia (LA)",
        "college": "Mississippi State",
        "college_conf": "Southeastern Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1413343"
    }, {
        "id": "e627dd8c-8b33-4a26-829f-5aeceefe57f9",
        "name": "Austin Faoliu",
        "jersey": "58",
        "last_name": "Faoliu",
        "first_name": "Austin",
        "abbr_name": "A.Faoliu",
        "weight": 300.0,
        "height": 75,
        "position": "DT",
        "birth_place": "Santa Ana, CA, USA",
        "high_school": "Mater Dei (CA)",
        "college": "Oregon",
        "status": "ACT",
        "sr_id": "sr:player:2198398"
    }, {
        "id": "f5b61bef-6214-4d70-9a34-d58da29ce2d5",
        "name": "Tyler Biadasz",
        "jersey": "63",
        "last_name": "Biadasz",
        "first_name": "Tyler",
        "abbr_name": "T.Biadasz",
        "preferred_name": "Tyler",
        "birth_date": "1998-11-20",
        "weight": 320.0,
        "height": 75,
        "position": "C",
        "birth_place": "Amherst, WI, USA",
        "high_school": "Amherst (WI)",
        "college": "Wisconsin",
        "college_conf": "Big Ten Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2042665",
        "draft": {
            "year": 2020,
            "round": 4,
            "number": 146,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "f9c86838-11e5-4582-a03e-c15e02b2013c",
        "name": "Damontae Kazee",
        "jersey": "35",
        "last_name": "Kazee",
        "first_name": "Damontae",
        "abbr_name": "D.Kazee",
        "preferred_name": "Damontae",
        "birth_date": "1993-06-05",
        "weight": 190.0,
        "height": 71,
        "position": "SAF",
        "birth_place": "San Bernardino, CA, USA",
        "high_school": "Cajon (CA)",
        "college": "San Diego State",
        "college_conf": "Mountain West Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1130081",
        "draft": {
            "year": 2017,
            "round": 5,
            "number": 149,
            "team": {
                "id": "e6aa13a4-0055-48a9-bc41-be28dc106929",
                "name": "Falcons",
                "market": "Atlanta",
                "alias": "ATL",
                "sr_id": "sr:competitor:4393"
            }
        }
    }, {
        "id": "fb48038c-8f33-47a5-abb4-cda19f66c853",
        "name": "Sewo Olonilua",
        "jersey": "45",
        "last_name": "Olonilua",
        "first_name": "Sewo",
        "abbr_name": "S.Olonilua",
        "preferred_name": "Sewo",
        "birth_date": "1997-11-27",
        "weight": 240.0,
        "height": 75,
        "position": "FB",
        "birth_place": "Kingwood, TX, USA",
        "high_school": "Kingwood (TX)",
        "college": "Texas Christian",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1220138"
    }, {
        "id": "fc833ad5-955b-4129-9280-63d8eda84df2",
        "name": "Azur Kamara",
        "jersey": "43",
        "last_name": "Kamara",
        "first_name": "Azur",
        "abbr_name": "A.Kamara",
        "preferred_name": "Azur",
        "birth_date": "1996-01-01",
        "weight": 235.0,
        "height": 76,
        "position": "LB",
        "birth_place": "Glendale, AZ, USA",
        "high_school": "Central (AZ)",
        "college": "Kansas",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:1419751"
    }, {
        "id": "fda10175-38e3-4678-a94c-ccd6008d40ec",
        "name": "Neville Gallimore",
        "jersey": "96",
        "last_name": "Gallimore",
        "first_name": "Neville",
        "abbr_name": "N.Gallimore",
        "preferred_name": "Neville",
        "birth_date": "1997-01-17",
        "weight": 302.0,
        "height": 74,
        "position": "DT",
        "birth_place": "St. Catherines, ON, CAN",
        "high_school": "Canada Prep Football Academy (CAN)",
        "college": "Oklahoma",
        "college_conf": "Big Twelve Conference",
        "rookie_year": 2020,
        "status": "ACT",
        "sr_id": "sr:player:2040519",
        "draft": {
            "year": 2020,
            "round": 3,
            "number": 82,
            "team": {
                "id": "e627eec7-bbae-4fa4-8e73-8e1d6bc5c060",
                "name": "Cowboys",
                "market": "Dallas",
                "alias": "DAL",
                "sr_id": "sr:competitor:4392"
            }
        }
    }, {
        "id": "fed820cc-3104-431a-b38c-efa192216035",
        "name": "Eric Smith",
        "jersey": "67",
        "last_name": "Smith",
        "first_name": "Eric",
        "abbr_name": "E.Smith",
        "preferred_name": "Eric",
        "birth_date": "1995-09-02",
        "weight": 308.0,
        "height": 76,
        "position": "OT",
        "birth_place": "Decatur, GA, USA",
        "high_school": "Columbia (GA)",
        "college": "Virginia",
        "college_conf": "Atlantic Coast Conference",
        "rookie_year": 2017,
        "status": "ACT",
        "sr_id": "sr:player:1220418"
    }],
    "_comment": "Generation started @ 2021-08-12 03:08:15 UTC ended @ 2021-08-12 03:08:16 UTC"
}